# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2021 Adriaan de Groot <groot@kde.org>

name: 'Generic Build'
description: 'Configure, build and install the sources'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        test -n "$BUILDDIR" || { echo "! \$BUILDDIR not set" ; exit 1 ; }
        mkdir -p $BUILDDIR
        test -f $SRCDIR/CMakeLists.txt || { echo "! Missing $SRCDIR/CMakeLists.txt" ; exit 1 ; }
        echo "::set-output name=git_summary::"`git log -1 --abbrev-commit --pretty=oneline --no-decorate ${{ github.event.head_commit.id }}`
    - shell: bash
      run: |
        cd "$BUILDDIR" && cmake $CMAKE_ARGS $SRCDIR
    - shell: bash
      run: |
        cd "$BUILDDIR" && make -j2 VERBOSE=1
    - shell: bash
      run: |
        cd "$BUILDDIR" && make install VERBOSE=1
