# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2021 Adriaan de Groot <groot@kde.org>

name: 'Prepare Debian'
description: 'Install build-dependencies on Debian Stable'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
          apt-get update
          apt-get -y install git-core jq
          apt-get -y install \
            build-essential \
            cmake \
            extra-cmake-modules \
            gettext \
            kio-dev \
            libatasmart-dev \
            libboost-python-dev \
            libkf5config-dev \
            libkf5coreaddons-dev \
            libkf5i18n-dev \
            libkf5iconthemes-dev \
            libkf5parts-dev \
            libkf5service-dev \
            libkf5solid-dev \
            libparted-dev \
            libpolkit-qt5-1-dev \
            libqt5svg5-dev \
            libqt5webkit5-dev \
            libyaml-cpp-dev \
            os-prober \
            pkg-config \
            python3-dev \
            qtbase5-dev \
            qtdeclarative5-dev \
            qttools5-dev \
            qttools5-dev-tools
          # Same name as on KDE neon, different version
          apt-get -y install libkpmcore-dev
          # Additional dependencies
          apt-get -y install \
            libappstreamqt-dev \
            libicu-dev \
            libkf5crash-dev \
            libkf5package-dev \
            libkf5plasma-dev \
            libpwquality-dev \
            libqt5webenginewidgets5 \
            qtwebengine5-dev

          
