# SPDX-License-Identifier: BSD-2-Clause
# SPDX-FileCopyrightText: 2021 Adriaan de Groot <groot@kde.org>

name: 'Notify on Push'
description: 'Notify Matrix room'

inputs:
  room:
    description: 'Matrix Room ID'
    required: true
  token:
    description: 'Matrix Token'
    required: true
  message:
    description: 'Message to send'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        MESSAGE: ${{ inputs.message }}
      run: |
        curl -s -XPOST -d "$( echo "$MESSAGE" | jq -Rsc '{"msgtype": "m.text", "body":@text}' )" "https://matrix.org/_matrix/client/r0/rooms/%21${{ inputs.room }}/send/m.room.message?access_token=${{ inputs.token }}" > /dev/null
